export const sideBarData = [
  {
    documentRootPath: '/docs',
    scanStartPath: 'base/JavaScript',
    resolvePath: 'base/JavaScript/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'base/TypeScript',
    resolvePath: 'base/TypeScript/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'frameWork/Vue',
    resolvePath: 'frameWork/Vue/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'frameWork/Vite',
    resolvePath: 'frameWork/Vite/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'frameWork/Experience',
    resolvePath: 'frameWork/Experience/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'frameWork/Webpack',
    resolvePath: 'frameWork/Webpack/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'frameWork/React',
    resolvePath: 'frameWork/React/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'forward/http',
    resolvePath: 'forward/http/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'forward/optimize',
    resolvePath: 'forward/optimize/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'forward/git',
    resolvePath: 'forward/git/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'forward/node',
    resolvePath: 'forward/node/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'expansion/AI',
    resolvePath: 'expansion/AI/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'expansion/Server',
    resolvePath: 'expansion/Server/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'expansion/Scenarios',
    resolvePath: 'expansion/Scenarios/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },

  {
    documentRootPath: '/docs',
    scanStartPath: 'interview/Examples',
    resolvePath: 'interview/Examples/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'interview/CSS',
    resolvePath: 'interview/CSS/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'interview/Algorithm',
    resolvePath: 'interview/Algorithm/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'interview/JavaScript',
    resolvePath: 'interview/JavaScript/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs',
    scanStartPath: 'interview/ScenarioQuestion',
    resolvePath: 'interview/ScenarioQuestion/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
  {
    documentRootPath: '/docs/',
    scanStartPath: 'interview/HTML',
    resolvePath: 'interview/HTML/',
    useTitleFromFileHeading: true,
    useTitleFromFrontmatter: true,
    frontmatterTitleFieldName: 'title',
    hyphenToSpace: true,
    underscoreToSpace: true,
    collapsed: false,
    collapseDepth: 2,
  },
];
